/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ericsson_eniqanalysis_probing_jni_StapleJniInterface */

#ifndef _Included_com_ericsson_eniqanalysis_probing_jni_StapleJniInterface
#define _Included_com_ericsson_eniqanalysis_probing_jni_StapleJniInterface
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: logger */
/*
 * Class:     com_ericsson_eniqanalysis_probing_jni_StapleJniInterface
 * Method:    startStaple
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;ZILjava/lang/String;Ljava/lang/String;ZZZI)V
 */
JNIEXPORT void JNICALL Java_com_ericsson_eniqanalysis_probing_jni_StapleJniInterface_startStaple
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jint, jstring, jboolean, jint, jstring, jstring, jboolean, jboolean, jboolean, jint);

/*
 * Class:     com_ericsson_eniqanalysis_probing_jni_StapleJniInterface
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ericsson_eniqanalysis_probing_jni_StapleJniInterface_terminate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
